# Generated by Django 5.2.6 on 2025-09-24 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('GR', 'Guia de Remessa'), ('FT', 'Fatura')], default='GR', max_length=2)),
                ('number', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='inbound/')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_payload', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_ref', models.CharField(max_length=120)),
                ('issue', models.CharField(max_length=255)),
                ('suggested_internal_sku', models.CharField(blank=True, max_length=120)),
                ('suggested_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='rececao.inbounddocument')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('certified_id', models.CharField(blank=True, max_length=64)),
                ('inbound', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_result', to='rececao.inbounddocument')),
            ],
        ),
        migrations.AddField(
            model_name='inbounddocument',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rececao.purchaseorder'),
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=120)),
                ('maybe_internal_sku', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(default='UN', max_length=20)),
                ('qty_received', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rececao.inbounddocument')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='rececao.supplier'),
        ),
        migrations.AddField(
            model_name='inbounddocument',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_docs', to='rececao.supplier'),
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_sku', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(default='UN', max_length=20)),
                ('qty_ordered', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tolerance', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rececao.purchaseorder')),
            ],
            options={
                'unique_together': {('po', 'internal_sku')},
            },
        ),
        migrations.CreateModel(
            name='CodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=120)),
                ('internal_sku', models.CharField(max_length=120)),
                ('confidence', models.FloatField(default=1.0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_mappings', to='rececao.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'supplier_code')},
            },
        ),
    ]
