# Generated by Django 5.0.6 on 2025-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rececao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='article_code',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
