# Generated by Django 5.0.6 on 2025-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rececao', '0002_receiptline_article_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemapping',
            name='qty_ordered',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
