# Generated by Django 5.0.6 on 2025-10-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rececao', '0003_codemapping_qty_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(blank=True, max_length=50)),
                ('mini_codigo', models.CharField(db_index=True, max_length=120, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('designacao', models.CharField(max_length=500)),
                ('identificador', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Mini Código',
                'verbose_name_plural': 'Mini Códigos',
                'ordering': ['familia', 'mini_codigo'],
            },
        ),
        migrations.AlterField(
            model_name='codemapping',
            name='qty_ordered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='exceptiontask',
            name='suggested_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inbounddocument',
            name='doc_type',
            field=models.CharField(choices=[('GR', 'Guia de Remessa'), ('FT', 'Nota de Encomenda')], default='GR', max_length=2),
        ),
        migrations.AlterField(
            model_name='inbounddocument',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_docs', to='rececao.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='poline',
            name='qty_ordered',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='poline',
            name='tolerance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='qty_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
