# Generated by Django 5.0.6 on 2025-10-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rececao', '0004_minicodigo_alter_codemapping_qty_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poline',
            name='qty_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
