# Generated by Django 5.0.6 on 2025-10-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rececao', '0005_poline_qty_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='po_number_extracted',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
