# Generated by Django 5.0.6 on 2025-10-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rececao', '0006_receiptline_po_number_extracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='po_number_extracted',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
